baseURL = "https://www.guruonline.web.id/"
languageCode = "id-id"
title = "Media Online Guru Indonesia"
theme = "newsroom"
disqusShortname = "guru-online" # Pastikan shortname Disqus Anda hanya "guru-online" tanpa tanda kutip

[params]
  logo = "/images/logogo.png"
