baseURL = "https://guruonline.web.id/"
languageCode = "id-id"
title = "Media Online Guru Indonesia"
theme = "newsroom"
disqusShortname = "guru-online"

[params]
  # Tentukan path logo Anda. Path dimulai dari folder 'static'.
  # Jika logo ada di /static/images/logo-guru.png, maka pathnya adalah /images/logo-guru.png
  logo = "/images/logogo.png"
  
[menu]
  [[menu.main]]
    identifier = "tentang"
    name = "Tentang Kami"
    url = "/about/"           # URL tujuan (Asumsi Anda punya halaman /about/index.md)
    weight = 20

  [[menu.main]]
    identifier = "kontak"
    name = "Kontak"
    url = "/contact/"
    weight = 30  
	
  [[menu.main]]
    identifier = "berita"      # ID unik untuk item menu
    name = "Berita Terbaru"    # Teks yang akan ditampilkan
    url = "/posts/"            # URL tujuan (halaman daftar postingan)
    weight = 10                # Urutan (semakin kecil angkanya, semakin kiri)

  [[menu.main]]
    identifier = "artikel"      # ID unik untuk item menu
    name = "Artikel Terbaru"    # Teks yang akan ditampilkan
    url = "/artikel/"            # URL tujuan (halaman daftar postingan)
    weight = 10                # Urutan (semakin kecil angkanya, semakin kiri)	
	
  [[menu.main]]
    identifier = "opini"      # ID unik untuk item menu
    name = "opini Terbaru"    # Teks yang akan ditampilkan
    url = "/opini/"            # URL tujuan (halaman daftar postingan)
    weight = 10                # Urutan (semakin kecil angkanya, semakin kiri)	
	
  [[menu.main]]
    identifier = "kurikulum"      # ID unik untuk item menu
    name = "Bedah Kurikulum"    # Teks yang akan ditampilkan
    url = "/kurikulum/"            # URL tujuan (halaman daftar postingan)
    weight = 10                # Urutan (semakin kecil angkanya, semakin kiri)	
	
  [[menu.main]]
    identifier = "panduan"      # ID unik untuk item menu
    name = "Tutorial/Panduan"    # Teks yang akan ditampilkan
    url = "/panduan/"            # URL tujuan (halaman daftar postingan)
    weight = 10                # Urutan (semakin kecil angkanya, semakin kiri)	
	
  [[menu.main]]
    identifier = "benk-soal"      # ID unik untuk item menu
    name = "Kumpulan Soal"    # Teks yang akan ditampilkan
    url = "/bank-soal/"            # URL tujuan (halaman daftar postingan)
    weight = 10                # Urutan (semakin kecil angkanya, semakin kiri)	