baseURL = "https://www.guruonline.web.id/"
languageCode = "id-id"
title = "Media Online Guru Indonesia"
theme = "newsroom"
disqusShortname = "@disqus_zDuAHiZqBO"

# Jika Anda memiliki parameter lain (seperti menu, social, dll.), tambahkan di bawah sini.