baseURL = "https://www.guruonline.web.id/"
languageCode = "id-id"
title = "Media Online Guru Indonesia"
theme = "newsroom"
disqusShortname = "guru-online" 

[params]
  logo = "/images/logogo.png"
 
[menu]
  [[menu.main]]
    identifier = "berita"
    name = "Berita Terbaru"
    url = "/posts/berita"
    weight = 10 

  [[menu.main]]
    identifier = "artikel"
    name = "Artikel Terbaru"
    url = "posts/artikel/"
    weight = 20
    
  [[menu.main]]
    identifier = "opini"
    name = "Opini Terbaru"
    url = "posts/opini/"
    weight = 30
    
  [[menu.main]]
    identifier = "kurikulum"
    name = "Bedah Kurikulum"
    url = "posts/kurikulum/"
    weight = 40
    
  [[menu.main]]
    identifier = "panduan"
    name = "Tutorial/Panduan"
    url = "posts/panduan/"
    weight = 50
    
  [[menu.main]]
    identifier = "bank-soal" 
    name = "Kumpulan Soal"
    url = "posts/bank-soal/"
    weight = 60
    
  [[menu.main]]
    identifier = "tentang"
    name = "Tentang Kami"
    url = "/about/"
    weight = 90
    
  [[menu.main]]
    identifier = "kontak"
    name = "Kontak"
    url = "/contact/"
    weight = 100